server:
  port: 9004
  #Configurations H2
spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  #défini l'encodage pour data.sql
  datasource:
    sql-script-encoding: UTF-8

#on peut le mettre aussi dans le module applicationn du microservice produit car ce module à une dependance du module implementation, c'est pour cela je l'ai mis à 48 (config-product.limite=4)
config-product:
  limite: 2
